from infant.admin.infant_birth_admin import InfantBirthAdmin
from infant.admin.infant_birth_arv_admin import InfantBirthArvAdmin
from infant.admin.infant_birth_exam_admin import InfantBirthExamAdmin
from infant.admin.infant_birth_feeding_admin import InfantBirthFeedVaccineAdmin
from infant.admin.infant_circumcision_admin import InfantCircumcisionAdmin
from infant.admin.infant_congenital_anomalies_admin import (
    InfantCongenitalAnomalies, InfantCnsAbnormalityItemsAdmin,
    InfantFacialDefectItemsAdmin, InfantCleftDisorderItemsAdmin, InfantMouthUpGastrointestinalItemsAdmin,
    InfantCardiovascularDisorderItemsAdmin, InfantRespiratoryDefectItemsAdmin, InfantLowerGastrointestinalItemsAdmin,
    InfantFemaleGenitalAnomalyItemsAdmin, InfantMaleGenitalAnomalyItemsAdmin, InfantRenalAnomalyItemsAdmin,
    InfantMusculoskeletalAbnormalItemsAdmin, InfantSkinAbnormalItemsAdmin, InfantTrisomiesChromosomeItemsAdmin)
from infant.admin.infant_death_admin import InfantDeathAdmin
from infant.admin.infant_eligibility_admin import InfantEligibilityAdmin
from infant.admin.infant_off_study_admin import InfantOffStudyAdmin
from infant.admin.infant_visit_admin import InfantVisitAdmin
from infant.admin.infant_arv_proph_admin import InfantArvProphAdmin, InfantArvProphModAdmin
from infant.admin.infant_fu_admin import InfantFuAdmin
from infant.admin.infant_fu_dx_admin import InfantFuDxAdmin
from infant.admin.infant_fu_dx_items_admin import InfantFuDxItemsAdmin
from infant.admin.infant_fu_immunizations_admin import InfantFuImmunizationsAdmin
from infant.admin.infant_fu_new_med_admin import InfantFuNewMedAdmin
from infant.admin.infant_fu_new_med_items_admin import InfantFuNewMedItemsAdmin
from infant.admin.infant_fu_physical_admin import InfantFuPhysicalAdmin
