language: python
python:
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "nightly"
env:
  - DJANGO_VERSION=1.6
#  - DJANGO_VERSION=1.7
#  - DJANGO_VERSION=1.8


addons:
  apt_packages:
     - swig
     # - python-m2crypto
     - libssl-dev
     - libssl0.9.8

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

install:
  # - sudo apt-get install swig libssl-dev libssl0.9.8
  - pip install --upgrade pip
  - pip install -q Django==$DJANGO_VERSION
  - pip install flake8
  - pip install coveralls
  - pip install M2Crypto
  - pip install -q -r requirements.txt

before_script:
  - flake8 bhp077

script: 
  - coverage run --source=bhp077 manage.py test

after_success:
  - coveralls
