CESAREAN = 'cesarean'
LIVE = 'live birth'
NO_MODIFICATIONS = 'no_mod'
STILL_BIRTH = 'still birth'
VAGINAL = 'vaginal'
START = 'start'
BREASTFEED_ONLY = 'Breastfeeding only'
MIN_AGE_OF_CONSENT = 18
MAX_AGE_OF_CONSENT = 50
